### PR TITLE
Allow React 16

### PR DESCRIPTION
**Pull request by richardvenneman**
Tested and found working in our React 16 app

### CODE REVIEW

**Comment by sshadmand** [comment]
Thanks @richardvenneman.

@wbinnssmith, Looking forward to getting this merged in :-D

**Comment by PaulInglis** [comment]
Can this be merged please?

**Comment by danactive** [comment]
@wbinnssmith Poke, please merge

**Comment by wbinnssmith** [comment]
Done. Apologies for the delay!

**Comment by danactive** [comment]
@wbinnssmith Hey one more ask, will you bump the version and npm publish?

**Comment by wbinnssmith** [comment]
done! Apologies again -- I hope to be more actively maintaining this project. Let me know if anyone else wants to help out!

**Comment by arnaldomoschetto** [comment]
Hey @wbinnssmith, thanks for that, could you please upgrade same peerDependecies to react 17 or doesn't explicit a specific react version?

**Pull request merged**
